// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF8Xi-gL3aqzHpb76Bep1hP1H4N8jygSs',
    appId: '1:620343386463:web:64e17d820705dd2f2c16ea',
    messagingSenderId: '620343386463',
    projectId: 'food-473cf',
    authDomain: 'food-473cf.firebaseapp.com',
    storageBucket: 'food-473cf.firebasestorage.app',
    measurementId: 'G-YJWS0G35J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Rk2ZCS6OgAQF3pxDpXEpfoKadpNZrKM',
    appId: '1:620343386463:android:6e5ac977a59d7d4d2c16ea',
    messagingSenderId: '620343386463',
    projectId: 'food-473cf',
    storageBucket: 'food-473cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2LRhWR3KcbF1n03Tez7cBVKucnlrgxdQ',
    appId: '1:620343386463:ios:db5a3672f3b369e62c16ea',
    messagingSenderId: '620343386463',
    projectId: 'food-473cf',
    storageBucket: 'food-473cf.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2LRhWR3KcbF1n03Tez7cBVKucnlrgxdQ',
    appId: '1:620343386463:ios:db5a3672f3b369e62c16ea',
    messagingSenderId: '620343386463',
    projectId: 'food-473cf',
    storageBucket: 'food-473cf.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF8Xi-gL3aqzHpb76Bep1hP1H4N8jygSs',
    appId: '1:620343386463:web:af0a6a511c2a36ba2c16ea',
    messagingSenderId: '620343386463',
    projectId: 'food-473cf',
    authDomain: 'food-473cf.firebaseapp.com',
    storageBucket: 'food-473cf.firebasestorage.app',
    measurementId: 'G-8M19GYL4BF',
  );
}
